### ISSUE TITLE
Invalid compressed folder

### ISSUE THREAD

**Issue by masalt2** [TPEcool/beeMMX-R#1]
When I try to open or unzip the folder, Windows throws an error popup saying it's an invalid compressed folder.

![error1](https://github.com/TPEcool/beeMMX-R/assets/122125545/d812b3f1-9c16-43c3-a14e-49e0fb41bb71)
![error2](https://github.com/TPEcool/beeMMX-R/assets/122125545/a66af729-b2d8-4e6c-b5da-405115ea1923)

**Comment by TPEcool** [comment]
Oh, sorry, i thought it works. Gonna fix it ASAP.

**Comment by TPEcool** [comment]
Thanks for reporting, the download has been fixed. Please redownload the application to run it.
