### ISSUE TITLE
BEEMod will refuse to launch if "None" is selected for "Style".

### ISSUE THREAD

**Issue by Super82553** [TPEcool/beeMMX-R#13]
BEEMod will give an error when launching, if the compiled package has "None" selected as the style for a track.
This happens, because the info.txt file in the package has an "Overrides" thing, that has no end ( } ).

**Comment by TPEcool** [comment]
Did you have several tracks with a style specified and one with None style or all were None?

**Comment by Super82553** [comment]
All of them were "None".

**Comment by TPEcool** [comment]
Thanks for the information. I will try to find and fix the issue now.
